# SPDX-License-Identifier: GPL-2.0

KERNEL_SRC ?= /lib/modules/$(shell uname -r)/build
M ?= $(shell pwd)

KBUILD_OPTIONS	+= CONFIG_AOC_DRIVER=m CONFIG_WC_MBOX=m \
		  CONFIG_AOC_CHAR_DRIVER=m CONFIG_AOC_CHAN_DRIVER=m \
		  CONFIG_AOC_CONTROL_DRIVER=m CONFIG_AOC_UWB_DRIVER=m \
		  CONFIG_AOC_TBN_DRIVER=m CONFIG_AOC_UNIT_TEST_DRIVER=m \

include $(KERNEL_SRC)/../../../../private/google-modules/soc/gs/Makefile.include

-include $(KERNEL_SRC)/../../../../private/google-modules/Makefile.include

modules modules_install clean compile_commands.json:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) \
